### ISSUE TITLE
viewのモックを作る

### ISSUE THREAD

**Issue by TetsuyaNegishi** [TetsuyaNegishi/ngs-ichikawa#1]
# What/Why
viewのモックを作る

# Acceptance Criteria
- トップページの投稿ボタンをタップするとカメラページに移動する
- キャンセルをタップするとトップページに戻る

# Reference
[Onsen UIチュートリアル](http://tutorial.onsen.io/?framework=vue&category=reference&module=navigator)

# ToDo
- [x] OnsenUI をプロジェクトに追加
- [x] 画面を作る

**Comment by ghost** [comment]
finished
