### ISSUE TITLE
ブラウザでの表示とAndroid（実機）でのデザインが違いすぎる

### ISSUE THREAD

**Issue by ghost** [TetsuyaNegishi/ngs-ichikawa#3]
# What/Why
デザインが意図した通りのものになっているかを確認するため
開発効率を上げるため（ブラウザ上でデザインの変更・確認をする）

# Acceptance Criteria
- ブラウザでの表示と実機でのデザインが一致している

# Reference

# ToDo

**Comment by TetsuyaNegishi** [comment]
ons.forcePlatformStyling('ios');
でできるっぽい。

参考：
https://teratail.com/questions/60719
https://ja.onsen.io/v2/docs/js/ons.html#method-forcePlatformStyling
