### ISSUE TITLE
ユーザはログイン画面でログイン情報を入力できる

### ISSUE THREAD

**Issue by TetsuyaNegishi** [TetsuyaNegishi/ngs-ichikawa#34]
# User Story
ユーザはログイン画面でログイン情報を入力できる

# Acceptance Criteria
- [x] アプリを起動するとログイン画面が表示される
- [x] 間違っているユーザ情報を入力した時にログインできない（エラーメッセージを表示する）
- [x] 正しいユーザ情報を入力したときにトップページに遷移する

# Reference
[完了定義シート](https://docs.google.com/spreadsheets/d/1TUeZSbTxRTHgyhwOPrhG1eF8r5npHGotrrEvdBJ8uBE/edit#gid=0)

# ToDo
- [x] vue-routerを導入する
- [x] ログインページのコーディング
- [x] ログインを失敗した場合にポップアップでメッセージを表示する
- [x] ログインに成功した場合にトップページに遷移させる(vue-routerで切り替えられるようにする)

**Comment by ghost** [comment]
ok
